### ISSUE TITLE
Missing texture/model for Directional Desublimator Blockstate

### ISSUE THREAD

**Issue by michelegargiulo** [SirStendec/WirelessUtilities#42] opened 2019-06-18 23:45 UTC
Minor graphical issue. Block works fine.
I attached an image to better explain what happens. 

It does not happen for the other blocks in the mod. The block displays the classic missing texture texture with an error message on top. The block is a Directional Desublimator (Tier 4, but happened with the other tiers too).

It has 4 augments (Inverter, World, Range T1, Capacity T3).

IO Control set to auto-output to top.

Image:
![2019-06-19_01 24 17](https://user-images.githubusercontent.com/8409482/59726248-34e53480-9231-11e9-94f1-4c9f733d9ade.png)

F3 debug info:
![2019-06-19_01 43 40](https://user-images.githubusercontent.com/8409482/59726905-d077a480-9233-11e9-88d9-109d89dddde7.png)

**Comment by Lordmau5** [comment] 2019-06-19 01:51
I'm unsure if this is actually a new bug or one that we fixed in a previous version already because it does look familiar...

Would you mind telling us which version of the mod you are on?
I would assume the newest, so 1.7.76 at the time of writing this, but I just want to make sure :)

**Comment by michelegargiulo** [comment] 2019-06-19 09:03
Yes, I am running 1.7.76, forgot to include that info, sorry

**Comment by Lordmau5** [comment] 2019-06-19 22:28
Alright I've tried reproducing it but couldn't... It's working fine over here, so my assumption now is that some mod is interfering with our mod (not unlikely when you have ~250 installed mods in packs nowadays, heh)

Anyway, would you mind sharing the list of mods you used (or maybe even the modpack, would make trying to reproduce it easier) and also a log of your game?

**Comment by michelegargiulo** [comment] 2019-06-19 22:38
sure. This is latest.log
[latest.log](https://github.com/SirStendec/WirelessUtilities/files/3308091/latest.log)

and this is the zip file containing the mods, configs and scripts (custom modpack)
https://mega.nz/#!bAJkEQ5R!DM0YdD7_fS7Z5TO8aSuLOrUYbd1FVKJnlk6FxP3Zx6s

**Comment by Lordmau5** [comment] 2019-06-19 22:43
Alright, whilst I'm getting the pack setup so I can test it afterwards, do you mind uploading the debug.log file as well?

The latest.log didn't show anything interesting...

Also, the debug.log from the client, in case you are playing on a dedicated server :P

//EDIT: Also, the download link isn't working, hehe

**Comment by michelegargiulo** [comment] 2019-06-19 22:46
Not playing on dedicated server. Also the download link works for me. Are you downloading the file to your computer or importing into your Mega account?

[debug.log](https://github.com/SirStendec/WirelessUtilities/files/3308120/debug.log)

**Comment by Lordmau5** [comment] 2019-06-19 22:48
> Are you downloading the file to your computer or importing into your Mega account?

Jesus christ they changed their bloody website to have the download button at the top when you're not logged in. Idiots.
Yeah, I'm downloading it now haha

**Comment by michelegargiulo** [comment] 2019-06-19 22:54
haha don't worry, happens to everyone the first time I send them Mega links.

**Comment by Lordmau5** [comment] 2019-06-20 01:34
Alright, so I've spent the last 2 hours butchering the 346-mod modpack and I've managed to trace it back to JourneyMap.

Trying to get in touch with the devs of that to figure out why this is happening.
Not necessarily helpful that they don't have their source code up anywhere >_>

**Comment by Lordmau5** [comment] 2019-06-20 22:25
And with that, it's resolved.
Well, kinda...

I've talked with both covers and the JourneyMap developers and it ended up being a bug within JourneyMap.

Will be fixed in the next beta release :)

![image](https://user-images.githubusercontent.com/1345036/59885274-05faca00-93bb-11e9-913f-96689cfa5257.png)

**Closed as completed by Lordmau5** 2019-06-20 22:25 UTC
Labels: bug, fixed in-dev
