### ISSUE TITLE
Directional sublimator with World and Inverted augment got stuck

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#16] opened 2019-05-09 10:26 UTC
I don't know what happened, it picked up a few items then stopped and for some reasons the maximum power is showing 61k as maximum power.
Blockdata: 
```
{RS:{Mode:0b,Level:0b,Power:0b},RotationX:0b,Owner:"Insane96MCP",Facing:1b,RangeWidth:7b,TransferSide0:2b,TransferSide1:0b,IterationMode:0b,OwnerUUIDLeast:-4763111030784581344L,Energy:25000L,TransferSide4:0b,OwnerUUIDMost:-7310722959868804726L,Version:"1.6",TransferSide5:0b,TransferSide2:0b,TransferSide3:0b,id:"wirelessutils:tile_directional_desublimator",OffsetHorizontal:0b,Locks:[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],RangeHeight:1b,Active:0b,OffsetVertical:0b,x:-999,y:96,z:-949,Level:4b,Augments:[{Slot:0,id:"wirelessutils:world_augment",Count:1b,Damage:0s},{Slot:1,id:"wirelessutils:capacity_augment",Count:1b,Damage:2s},{Slot:2,id:"wirelessutils:range_augment",Count:1b,Damage:4s},{Slot:3,id:"wirelessutils:invert_augment",Count:1b,Damage:0s},{Slot:4,id:"wirelessutils:transfer_augment",Count:1b,Damage:2s}],RangeLength:7b}
```
Level's stats are:
```js

resonant.budgetPerTick = 1;
resonant.maxBudget = (160 / 4.0) as int;
resonant.costPerItem = (160 / 4.0) as int;
```
Config is set to use 10RF/t per block distance and maximum cost at 1500
![2019-05-09_12 23 01](https://user-images.githubusercontent.com/7185104/57446696-99d26580-7255-11e9-8fb2-ebf2ce955ddc.png)
![2019-05-09_12 23 05](https://user-images.githubusercontent.com/7185104/57446633-6e4f7b00-7255-11e9-8f1c-ae036e569918.png)
![2019-05-09_12 23 30](https://user-images.githubusercontent.com/7185104/57446634-6e4f7b00-7255-11e9-8584-c93d41ca7def.png)

After a while items despawned but the Desublimator is still stuck like this. Rejoining the world or picking up and placing down the machine will do nothing

**Comment by SirStendec** [comment] 2019-05-09 20:54
The displayed maximum power sounds right for how it's calculated right now. The part responsible for rendering that doesn't know how many targets it can visit per tick, so it just adds up all the costs. It's a bit stupid, but it's what I've got for now.

I'm not able to reproduce the machine failing to pick up items, but I'm going to keep trying. Thanks for all the reports.

**Comment by SirStendec** [comment] 2019-05-09 23:15
I do have one idea for why this could be happening. The way item pick-ups work right now is that desublimators only try to do that every 10 ticks. Additionally, all our blocks only hit a certain number of possible block targets per tick. So if none of those positions line up on the gather tick, then it won't grab any items.

I'll need to think about a better way to handle the gather cooldown to make things work. Possibly just removing targets with no items until the next target update calculation re-adds them.

**Comment by SirStendec** [comment] 2019-05-10 17:59
If you can still reproduce this, can you use `/wu_debug` to get a Debug Bed, right click the misbehaving Desublimator with it, and then send me the section of the server log that generates? I have an idea why it might be happening, but I'd like to double check with your machine's internal state.

**Comment by SirStendec** [comment] 2019-05-10 18:56
This should theoretically be fixed on the latest build. I've changed how Directional Desublimators target item entities. I also found a bug with desublimators not updating cached data properly, which made them stop working. I believe that was limited to ones that drop items into the world, but I'm not absolutely certain.

If you can still reproduce this, I am still interested in your debug output.

**Comment by Insane96** [comment] 2019-05-11 07:23
![2019-05-11_09 12 28](https://user-images.githubusercontent.com/7185104/57566567-4df6fc00-73ce-11e9-897e-4f3d89e12d63.png)
Tried to reproduce that again, sadly I removed the stuck Desublimator, but seems like I can't reproduce it / it's fixed. The only question I have is, why active target shows 190?

**Comment by SirStendec** [comment] 2019-05-11 15:54
198 should be the number of air blocks within the working area you've set for the machine. A Desublimator with a World Augment only iterates over air blocks, on the assumption that other blocks won't contain item entities. I should probably work out some sort of solid block check, rather than just if it's air, but it works for now.

Of course, Directional Desublimators now just check their whole area at once, so they'll grab from solid blocks and the active targets number is slightly misleading.

I'm going to close this for now since no one is able to reproduce it at this time. Hopefully it really is fixed.

**Closed as completed by SirStendec** 2019-05-11 15:54 UTC
